### ISSUE TITLE
Версия minSdk

### ISSUE THREAD

**Issue by svsorokina** [mailru/mail-auth-sdk-android#1]
Добрый день!

Есть ли возможность понизить минимальную версию sdk до 16? Мы до сих пор поддерживаем приложения на android 4.1 и очень ждали релиз sdk. Хотелось бы использовать его у нас в приложении.

**Comment by Nestira** [comment]
Me too!. Our application also need to support minSdk 16 and I tried to lower this project to 16, everything seems ok. Could you please make it 16? Love you guys!

**Comment by govorovsky** [comment]
Hello!
We are working on support for minSdk 16. Will be available in next versions.

**Comment by govorovsky** [comment]
fixed in 11.3.0.28375
